import type { Metadata } from "next";
import { Poppins, Open_Sans, Raleway } from "next/font/google";
import "./globals.css";
import toast, { Toaster } from "react-hot-toast";


const raleway = Raleway({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
});

const openSans = Open_Sans({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-openSans",
});

export const metadata: Metadata = {
  title: "Safe-link",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className}`}>
        <Toaster />
          {children}
      </body>
    </html>
  );
}
