import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Image from "next/image";
import { Nav, NavLink } from "@/components/Nav";
import Footer from "@/components/Footer";
import Drawer from "@/components/Drawer";
import LoginForm from "@/components/LoginForm";
import SignupForm from "@/components/SignupForm";
import Modal from "@/components/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Safe-link",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav>
          <NavLink href={"/create-listing"}>List With Us</NavLink>
          <NavLink href={"/pricing"}>Pricing</NavLink>

          {/* <NavLink href={"/null"}>Log In</NavLink> */}

          {/* <NavLink href={"/signup"}>Sign Up</NavLink> */}
        </Nav>
        {children}
        <Drawer />
        {/* <Modal>
          <LoginForm />
        </Modal>
        <Modal>
        <SignupForm/>
        </Modal> */}
        <Footer />
      </body>
    </html>
  );
}
